"""Exact-rational homogeneous Fer recipes (generated; do not edit).

Generated by ``tools/generate_fer_coefficients.py`` using Hofstaetter's
BCH program: https://github.com/HaraldHofstaetter/BCH
Source revision: d84ed5d3b77ce14c637f30963972ee6719ee2857
"""

from __future__ import annotations

from typing import TypeAlias

LieWord: TypeAlias = int | tuple["LieWord", "LieWord"]
FerTerm: TypeAlias = tuple[int, int, LieWord]

FER_MAX_DEPTH = 6
FER_FACTORS: tuple[tuple[FerTerm, ...], ...] = (
    ((1, 1, 0),),
    ((1, 1, 1),),
    (
        (1, 1, 2),
        (-1, 2, (0, 1)),
    ),
    (
        (1, 1, 3),
        (-1, 2, (0, 2)),
        (1, 6, (0, (0, 1))),
    ),
    (
        (1, 1, 4),
        (-1, 2, (0, 3)),
        (-1, 2, (1, 2)),
        (1, 6, (0, (0, 2))),
        (-1, 3, ((0, 1), 1)),
        (-1, 24, (0, (0, (0, 1)))),
    ),
    (
        (1, 1, 5),
        (-1, 2, (0, 4)),
        (-1, 2, (1, 3)),
        (1, 6, (0, (0, 3))),
        (-1, 12, (0, (1, 2))),
        (-5, 12, ((0, 2), 1)),
        (-1, 24, (0, (0, (0, 2)))),
        (1, 8, (0, ((0, 1), 1))),
        (1, 120, (0, (0, (0, (0, 1))))),
    ),
)

__all__ = ["FER_FACTORS", "FER_MAX_DEPTH", "LieWord"]
